services:
  app:
    build: .
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_HTTP_PORT=3005
    network_mode: host
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
