global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'receipt-app'
    static_configs:
      - targets: ['localhost:3000']
        labels:
          app: 'receipt-tracker'
    metrics_path: '/metrics'
    scrape_timeout: 4s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3005']